services:
  my_database:
    image: mysql
    container_name: sql
    restart: always
    ports:
      - 3306:3306
    networks:
      - laiba_network
    volumes:
      - laiba_volume:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: laiba_db
      MYSQL_ROOT_PASSWORD: laiba

  admin_panel:
    image: adminer
    container_name: admin
    restart: always
    ports:
      - 9090:8080
    depends_on:
      - my_database
    networks:
      - laiba_network
    environment:
      ADMINER_DESIGN: hydra
      ADMINER_DEFAULT_SERVER: my_database

networks:
  laiba_network:

volumes:
  laiba_volume:
